server:
  port: 7000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: athena-product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.25.137:32081/athena_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
