#Spring service的属性
server:
  port: 8000
  servlet:
    session:
      timeout: 30m

# Spring的系列的属性
spring:
  #配置Spring服务的名称
  application:
    name: athena-coupon
  #配置Spring datebase的账户和连接
  datasource:
    username: root`
    password: root
    url: jdbc:mysql://192.168.25.137:32081/athena_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Springcloud alibaba nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.25.1:8848
        namespace: b4d48f9f-6c1a-4745-92c2-1ddcc11c5bbc

# mybatis-plus的系列的属性
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
